version: "3"
services:
  db:
    container_name: transactional_db
    image: postgres:14-alpine
    environment:
      #      TODO: remove and use secrets
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: transactional
    ports:
      - "54322:5432"